#!/usr/bin/env bash
# Deploy: pin the app to a concrete artifact build.
#
# Resolves the `latest` artifact symlink to its real target and writes it
# into ~/app/deployment-target.env, which both quadlet units read via
# EnvironmentFile. Restarts then stay pinned to that build; running this
# script again (after a new artifact is published) is what moves forward.
#
#   ./deploy.sh
set -euo pipefail

# where new artifacts are published (branch latest)
LATEST=/home/my-repos/artifacts/git-viewer/main/latest

APP_DIR="$HOME/app"
ENV_FILE="$APP_DIR/deployment-target.env"

REAL="$(realpath "$LATEST")"
if [[ ! -d "$REAL" ]]; then
	echo "artifact not found: $LATEST -> $REAL" >&2
	exit 1
fi

mkdir -p "$APP_DIR"
cat >"$ENV_FILE" <<EOF
# generated by deploy.sh — do not edit; run deploy.sh to re-pin
# the resolved artifact dir the units mount / execute from
ARTIFACT_DIR=$REAL
EOF
chmod 644 "$ENV_FILE"

echo "pinned: $LATEST -> $REAL ($ENV_FILE)"

# quadlet expands \${ARTIFACT_DIR} at generation time, so regenerate units
systemctl --user daemon-reload

# bring the running app onto the pinned build
systemctl --user restart app.service
echo "restarted app.service"
